// Tour registry — maps routes to tour slugs + their step arrays.
//
// GENERATED by /joyride-studio skill. Everything between the GENERATED REGISTRY
// markers is regenerated on each `/joyride-studio` run; code outside the markers
// is preserved.

import type { Step } from 'react-joyride';

type JoyrideStep = Step;

interface TourEntry {
  /** Unique slug. Used as the localStorage completion key suffix. */
  tourSlug: string;
  /**
   * Human-readable name shown in the tour-menu dropdown and nav integrations.
   * Defaults to a titlecased version of tourSlug if omitted.
   */
  name?: string;
  /** Optional one-line description shown under the name in the menu. */
  description?: string;
  /**
   * Route pattern — exact ('/') or prefix ('/presentation/*').
   * First entry that (a) route-matches AND (b) passes shouldShow wins for
   * single-tour resolution; `getAvailableToursForPath` returns ALL matches.
   */
  route: string;
  /**
   * Extra predicate beyond route match. Use when multiple tours share a
   * route and only one should apply given current sub-state (e.g. idle vs
   * outline on '/'). Typically probes for the tour's anchor in the DOM:
   *   shouldShow: () =>
   *     typeof document !== 'undefined' &&
   *     !!document.querySelector('[data-tour-id="<slug>.1"]');
   */
  shouldShow?: () => boolean;
  steps: JoyrideStep[];
}

// ========== GENERATED REGISTRY (do not edit by hand) ==========
const TOUR_REGISTRY: TourEntry[] = [];
// ========== END GENERATED REGISTRY ==========

function matchesRoute(pattern: string, pathname: string): boolean {
  if (pattern === pathname) return true;
  if (pattern.endsWith('/*')) {
    const prefix = pattern.slice(0, -2);
    return pathname === prefix || pathname.startsWith(prefix + '/');
  }
  return false;
}

/**
 * Single-tour lookup — returns the first matching entry whose shouldShow
 * passes. Used by TourProvider to decide which tour is "currently active"
 * for autoStart purposes.
 */
function getTourForPath(pathname: string): TourEntry | null {
  for (const entry of TOUR_REGISTRY) {
    if (!matchesRoute(entry.route, pathname)) continue;
    if (entry.shouldShow && !entry.shouldShow()) continue;
    return entry;
  }
  return null;
}

/**
 * List-of-tours lookup — returns ALL matching entries whose shouldShow
 * passes. Used by the TourMenu / TourButton dropdown to show every tour
 * a user could replay on the current page.
 */
function getAvailableToursForPath(pathname: string): TourEntry[] {
  const out: TourEntry[] = [];
  for (const entry of TOUR_REGISTRY) {
    if (!matchesRoute(entry.route, pathname)) continue;
    if (entry.shouldShow && !entry.shouldShow()) continue;
    out.push(entry);
  }
  return out;
}

function listTours(): TourEntry[] {
  return TOUR_REGISTRY.slice();
}

/** Titlecase a slug: `landing.hero` → `Landing Hero`; `editor-default` → `Editor Default`. */
function defaultTourName(slug: string): string {
  return slug
    .split(/[.\-_]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export { getTourForPath, getAvailableToursForPath, listTours, defaultTourName };
export type { TourEntry, JoyrideStep };
